openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: 'Affiche les utilisateurs'
      operationId: afficheLesUtilisateurs
      description: ''
      parameters:
        -
          in: query
          name: name
          description: "Filtrer par nom de l'utilisateur."
          example: null
          required: false
          schema:
            type: string
            description: "Filtrer par nom de l'utilisateur."
            example: null
            nullable: false
        -
          in: query
          name: email
          description: "Filtrer par email de l'utilisateur."
          example: null
          required: false
          schema:
            type: string
            description: "Filtrer par email de l'utilisateur."
            example: null
            nullable: false
        -
          in: query
          name: profile
          description: "Filtrer par profile de l'utilisateur."
          example: null
          required: false
          schema:
            type: string
            description: "Filtrer par profile de l'utilisateur."
            example: null
            nullable: false
        -
          in: query
          name: with_events
          description: 'Afficher les evenements.'
          example: 'false'
          required: false
          schema:
            type: string
            description: 'Afficher les evenements.'
            example: 'false'
            nullable: false
        -
          in: query
          name: paginate
          description: 'Utiliser la pagination.'
          example: 'false'
          required: false
          schema:
            type: string
            description: 'Utiliser la pagination.'
            example: 'false'
            nullable: false
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Utilisateurs
      security: []
    post:
      summary: 'Créer un nouvelle utilisateur'
      operationId: crerUnNouvelleUtilisateur
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Utilisateurs
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "Le nom de l'utilisateur."
                  example: charles.gamligo
                  nullable: false
                email:
                  type: string
                  description: "La valeur de l'utilisateur."
                  example: charles.gamligo@cofinacorp.com
                  nullable: false
                password:
                  type: string
                  description: "L'heure de l'ancement de l'utilisateur."
                  example: P@sse123
                  nullable: false
                profile:
                  type: string
                  description: "Le profile de l'utilisateur."
                  example: admin
                  nullable: false
                picture:
                  type: string
                  description: "L'image de l'utilisateur."
                  example: '0'
                  nullable: false
      security: []
  '/api/user/{id}':
    get:
      summary: 'Affiche un utilsateur'
      operationId: afficheUnUtilsateur
      description: ''
      parameters:
        -
          in: query
          name: with_events
          description: 'Afficher les departements.'
          example: 'false'
          required: false
          schema:
            type: string
            description: 'Afficher les departements.'
            example: 'false'
            nullable: false
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Utilisateurs
      security: []
    put:
      summary: 'Mettre à jour un utilisateur'
      operationId: mettreJourUnUtilisateur
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Utilisateurs
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "Le nom de l'utilisateur."
                  example: charles.gamligo
                  nullable: false
                email:
                  type: string
                  description: "La valeur de l'utilisateur."
                  example: charles.gamligo@cofinacorp.com
                  nullable: false
                password:
                  type: string
                  description: "L'heure de l'ancement de l'utilisateur."
                  example: P@sse123
                  nullable: false
                profile:
                  type: string
                  description: "Le profile de l'utilisateur."
                  example: admin
                  nullable: false
                picture:
                  type: string
                  description: "L'image de l'utilisateur."
                  example: '0'
                  nullable: false
      security: []
    delete:
      summary: 'Supprime un utilisateur'
      operationId: supprimeUnUtilisateur
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Utilisateurs
      security: []
    parameters:
      -
        in: path
        name: id
        description: "Optional parameter. L'ID de l'utilisateur."
        required: true
        schema:
          type: integer
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: 1
  /api/user/update-password:
    put:
      summary: "Mettre à jour le mot de passe de l'utilisateur connecté utilisateur"
      operationId: mettreJourLeMotDePasseDeLutilisateurConnectUtilisateur
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - Utilisateurs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                  description: "L'ancien mot de passe de l'utilisateur."
                  example: tenetur
                  nullable: false
                new_password:
                  type: string
                  description: "Le nouveau mot de passe de l'utilisateur."
                  example: et
                  nullable: false
                new_password_confirmation:
                  type: string
                  description: "La confirmation du nouveau mot de passe de l'utilisateur."
                  example: ex
                  nullable: false
              required:
                - old_password
                - new_password
                - new_password_confirmation
      security: []
tags:
  -
    name: Utilisateurs
    description: "\nEndPoints pour gérer les utilisateurs"
