DROP TABLE "OPERATION_HIST";

CREATE TABLE "OPERATION_HIST" ("CODE_AGENCE" VARCHAR2(3 BYTE), "AGENCE" VARCHAR2(105 BYTE),"NO_COMPTE" VARCHAR2(12 BYTE), "COMPTE" VARCHAR2(105 BYTE),"MATRICULE" VARCHAR2(9 BYTE),"SOLDE" NUMBER DEFAULT 0,"NO_BATCH" VARCHAR2(9 BYTE),"REQUEST_DATE" DATE, "AMOUNT_DEBITED" NUMBER DEFAULT 0,"USER_ID" VARCHAR2(90 BYTE)) NO INMEMORY;

ALTER TABLE OPERATION_HIST RENAME TO OPERATION_HIST_FIRST;
